### ISSUE TITLE
malloc 에러일 때 앞에 malloc 해준 것도 free

### ISSUE THREAD

**Issue by MichelleJin12** [S0YKIM/DATA-STRUCTURE#5]
https://github.com/S0YKIM/DATA-STRUCTURE/blob/8a0380db4ed346089ef57dc5359455d0ba21a0d2/1.array.c#L16-L17

**Comment by S0YKIM** [comment]
맞네요 이 부분을 놓쳤네요...오류 발견 감사합니다!
