### ISSUE TITLE
함수 안에서는 NULL 로 초기화 해주어도, 함수가 끝나면 값이 날라가버립니다!

### ISSUE THREAD

**Issue by MichelleJin12** [S0YKIM/Data-structure#6]
https://github.com/S0YKIM/DATA-STRUCTURE/blob/8a0380db4ed346089ef57dc5359455d0ba21a0d2/1.array.c#L28-L30

**Comment by S0YKIM** [comment]
pList 를 그대로 가져와서 값만 복사된 것이 아니라 포인터로 가져와서 pList->pElement 널 초기화 해준 것인데도 함수가 끝나면 날아가나요?

**Comment by MichelleJin12** [comment]
넵! 주소값 자체를 바꾸려면 double pointer로 해야해요! 저 함수를 호출하는 다른 함수(ex. main)에서 값을 출력해보면 0으로 초기화되지 않은 것을 알 수 있어요!

**Comment by S0YKIM** [comment]
말씀 이해했어요 이중 포인터로 바꾸어서 해결하겠습니다 피드백 감사해요~!
